package com.seeu.user.model;

public class Classtimetable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chosencourses.userid
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chosencourses.courseid
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private String courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chosencourses.index
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private Integer index;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chosencourses.userid
     *
     * @return the value of chosencourses.userid
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chosencourses.userid
     *
     * @param userid the value for chosencourses.userid
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chosencourses.courseid
     *
     * @return the value of chosencourses.courseid
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chosencourses.courseid
     *
     * @param courseid the value for chosencourses.courseid
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chosencourses.index
     *
     * @return the value of chosencourses.index
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chosencourses.index
     *
     * @param index the value for chosencourses.index
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setIndex(Integer index) {
        this.index = index;
    }
}