package com.seeu.user.model;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.courseid
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private String courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.code
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.name
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.day
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.time
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.teacher
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.location
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.credit
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private Integer credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.week
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private String week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.remaining
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private Integer remaining;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.total
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lessons.user
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    private String user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.courseid
     *
     * @return the value of lessons.courseid
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public String getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.courseid
     *
     * @param courseid the value for lessons.courseid
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.code
     *
     * @return the value of lessons.code
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.code
     *
     * @param code the value for lessons.code
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.name
     *
     * @return the value of lessons.name
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.name
     *
     * @param name the value for lessons.name
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.day
     *
     * @return the value of lessons.day
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.day
     *
     * @param day the value for lessons.day
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setDay(String day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.time
     *
     * @return the value of lessons.time
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.time
     *
     * @param time the value for lessons.time
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.teacher
     *
     * @return the value of lessons.teacher
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.teacher
     *
     * @param teacher the value for lessons.teacher
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.location
     *
     * @return the value of lessons.location
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.location
     *
     * @param location the value for lessons.location
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.credit
     *
     * @return the value of lessons.credit
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.credit
     *
     * @param credit the value for lessons.credit
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.week
     *
     * @return the value of lessons.week
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.week
     *
     * @param week the value for lessons.week
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setWeek(String week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.remaining
     *
     * @return the value of lessons.remaining
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public Integer getRemaining() {
        return remaining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.remaining
     *
     * @param remaining the value for lessons.remaining
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setRemaining(Integer remaining) {
        this.remaining = remaining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.total
     *
     * @return the value of lessons.total
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.total
     *
     * @param total the value for lessons.total
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lessons.user
     *
     * @return the value of lessons.user
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lessons.user
     *
     * @param user the value for lessons.user
     *
     * @mbggenerated Thu Jun 15 01:55:09 CST 2017
     */
    public void setUser(String user) {
        this.user = user;
    }
}