package com.seeu.user.model;

public class GeneralCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.courseid
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private String courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.code
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.name
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.teacher
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.credit
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private Integer credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.week
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private String week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.day_detail1
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private String day_detail1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.day_detail2
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private String day_detail2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.location
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.remaining
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private Integer remaining;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.total
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.extra
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalcourseinformation.index
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    private Integer index;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.courseid
     *
     * @return the value of generalcourseinformation.courseid
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.courseid
     *
     * @param courseid the value for generalcourseinformation.courseid
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.code
     *
     * @return the value of generalcourseinformation.code
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.code
     *
     * @param code the value for generalcourseinformation.code
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.name
     *
     * @return the value of generalcourseinformation.name
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.name
     *
     * @param name the value for generalcourseinformation.name
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.teacher
     *
     * @return the value of generalcourseinformation.teacher
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.teacher
     *
     * @param teacher the value for generalcourseinformation.teacher
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.credit
     *
     * @return the value of generalcourseinformation.credit
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.credit
     *
     * @param credit the value for generalcourseinformation.credit
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.week
     *
     * @return the value of generalcourseinformation.week
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.week
     *
     * @param week the value for generalcourseinformation.week
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setWeek(String week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.day_detail1
     *
     * @return the value of generalcourseinformation.day_detail1
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String getDay_detail1() {
        return day_detail1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.day_detail1
     *
     * @param day_detail1 the value for generalcourseinformation.day_detail1
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setDay_detail1(String day_detail1) {
        this.day_detail1 = day_detail1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.day_detail2
     *
     * @return the value of generalcourseinformation.day_detail2
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String getDay_detail2() {
        return day_detail2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.day_detail2
     *
     * @param day_detail2 the value for generalcourseinformation.day_detail2
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setDay_detail2(String day_detail2) {
        this.day_detail2 = day_detail2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.location
     *
     * @return the value of generalcourseinformation.location
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.location
     *
     * @param location the value for generalcourseinformation.location
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.remaining
     *
     * @return the value of generalcourseinformation.remaining
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public Integer getRemaining() {
        return remaining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.remaining
     *
     * @param remaining the value for generalcourseinformation.remaining
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setRemaining(Integer remaining) {
        this.remaining = remaining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.total
     *
     * @return the value of generalcourseinformation.total
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.total
     *
     * @param total the value for generalcourseinformation.total
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.extra
     *
     * @return the value of generalcourseinformation.extra
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.extra
     *
     * @param extra the value for generalcourseinformation.extra
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setExtra(String extra) {
        this.extra = extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalcourseinformation.index
     *
     * @return the value of generalcourseinformation.index
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalcourseinformation.index
     *
     * @param index the value for generalcourseinformation.index
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    public GeneralCourse(String courseid, String code, String name, String teacher, Integer credit, String week, String day_detail1, String day_detail2, String location, Integer remaining, Integer total, String extra, Integer index) {
        this.courseid = courseid;
        this.code = code;
        this.name = name;
        this.teacher = teacher;
        this.credit = credit;
        this.week = week;
        this.day_detail1 = day_detail1;
        this.day_detail2 = day_detail2;
        this.location = location;
        this.remaining = remaining;
        this.total = total;
        this.extra = extra;
        this.index = index;
    }
}