package com.seeu.user.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.index
     *
     * @mbggenerated Sun Jun 18 22:18:51 CST 2017
     */
    private Integer index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.userid
     *
     * @mbggenerated Sun Jun 18 22:18:51 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.password
     *
     * @mbggenerated Sun Jun 18 22:18:51 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.index
     *
     * @return the value of userinformation.index
     *
     * @mbggenerated Sun Jun 18 22:18:51 CST 2017
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.index
     *
     * @param index the value for userinformation.index
     *
     * @mbggenerated Sun Jun 18 22:18:51 CST 2017
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.userid
     *
     * @return the value of userinformation.userid
     *
     * @mbggenerated Sun Jun 18 22:18:51 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.userid
     *
     * @param userid the value for userinformation.userid
     *
     * @mbggenerated Sun Jun 18 22:18:51 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.password
     *
     * @return the value of userinformation.password
     *
     * @mbggenerated Sun Jun 18 22:18:51 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.password
     *
     * @param password the value for userinformation.password
     *
     * @mbggenerated Sun Jun 18 22:18:51 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }
}