package com.seeu.user.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.user.model.Classtimetable;

public class ClasstimetableSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chosencourses
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String insertSelective(Classtimetable record) {
        BEGIN();
        INSERT_INTO("chosencourses");
        
        if (record.getUserid() != null) {
            VALUES("userid", "#{userid,jdbcType=VARCHAR}");
        }
        
        if (record.getCourseid() != null) {
            VALUES("courseid", "#{courseid,jdbcType=CHAR}");
        }
        
        if (record.getIndex() != null) {
            VALUES("index", "#{index,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chosencourses
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String updateByPrimaryKeySelective(Classtimetable record) {
        BEGIN();
        UPDATE("chosencourses");
        
        if (record.getCourseid() != null) {
            SET("courseid = #{courseid,jdbcType=CHAR}");
        }
        
        if (record.getIndex() != null) {
            SET("index = #{index,jdbcType=INTEGER}");
        }
        
        WHERE("userid = #{userid,jdbcType=VARCHAR}");
        
        return SQL();
    }
}