package com.seeu.user.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.user.model.Course;

public class CourseSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lessons
     *
     * @mbggenerated Thu Jun 15 01:55:10 CST 2017
     */
    public String insertSelective(Course record) {
        BEGIN();
        INSERT_INTO("lessons");
        
        if (record.getCourseid() != null) {
            VALUES("courseid", "#{courseid,jdbcType=VARCHAR}");
        }
        
        if (record.getCode() != null) {
            VALUES("code", "#{code,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=CHAR}");
        }
        
        if (record.getDay() != null) {
            VALUES("day", "#{day,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            VALUES("time", "#{time,jdbcType=CHAR}");
        }
        
        if (record.getTeacher() != null) {
            VALUES("teacher", "#{teacher,jdbcType=CHAR}");
        }
        
        if (record.getLocation() != null) {
            VALUES("location", "#{location,jdbcType=CHAR}");
        }
        
        if (record.getCredit() != null) {
            VALUES("credit", "#{credit,jdbcType=INTEGER}");
        }
        
        if (record.getWeek() != null) {
            VALUES("week", "#{week,jdbcType=VARCHAR}");
        }
        
        if (record.getRemaining() != null) {
            VALUES("remaining", "#{remaining,jdbcType=INTEGER}");
        }
        
        if (record.getTotal() != null) {
            VALUES("total", "#{total,jdbcType=INTEGER}");
        }
        
        if (record.getUser() != null) {
            VALUES("user", "#{user,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lessons
     *
     * @mbggenerated Thu Jun 15 01:55:10 CST 2017
     */
    public String updateByPrimaryKeySelective(Course record) {
        BEGIN();
        UPDATE("lessons");
        
        if (record.getCode() != null) {
            SET("code = #{code,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=CHAR}");
        }
        
        if (record.getDay() != null) {
            SET("day = #{day,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            SET("time = #{time,jdbcType=CHAR}");
        }
        
        if (record.getTeacher() != null) {
            SET("teacher = #{teacher,jdbcType=CHAR}");
        }
        
        if (record.getLocation() != null) {
            SET("location = #{location,jdbcType=CHAR}");
        }
        
        if (record.getCredit() != null) {
            SET("credit = #{credit,jdbcType=INTEGER}");
        }
        
        if (record.getWeek() != null) {
            SET("week = #{week,jdbcType=VARCHAR}");
        }
        
        if (record.getRemaining() != null) {
            SET("remaining = #{remaining,jdbcType=INTEGER}");
        }
        
        if (record.getTotal() != null) {
            SET("total = #{total,jdbcType=INTEGER}");
        }
        
        if (record.getUser() != null) {
            SET("user = #{user,jdbcType=VARCHAR}");
        }
        
        WHERE("courseid = #{courseid,jdbcType=VARCHAR}");
        
        return SQL();
    }
}