package com.seeu.user.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.seeu.user.model.GeneralCourse;

public class GeneralCourseSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generalcourseinformation
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String insertSelective(GeneralCourse record) {
        BEGIN();
        INSERT_INTO("generalcourseinformation");
        
        if (record.getCourseid() != null) {
            VALUES("courseid", "#{courseid,jdbcType=VARCHAR}");
        }
        
        if (record.getCode() != null) {
            VALUES("code", "#{code,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getTeacher() != null) {
            VALUES("teacher", "#{teacher,jdbcType=VARCHAR}");
        }
        
        if (record.getCredit() != null) {
            VALUES("credit", "#{credit,jdbcType=INTEGER}");
        }
        
        if (record.getWeek() != null) {
            VALUES("week", "#{week,jdbcType=VARCHAR}");
        }
        
        if (record.getDay_detail1() != null) {
            VALUES("day_detail1", "#{day_detail1,jdbcType=VARCHAR}");
        }
        
        if (record.getDay_detail2() != null) {
            VALUES("day_detail2", "#{day_detail2,jdbcType=VARCHAR}");
        }
        
        if (record.getLocation() != null) {
            VALUES("location", "#{location,jdbcType=VARCHAR}");
        }
        
        if (record.getRemaining() != null) {
            VALUES("remaining", "#{remaining,jdbcType=INTEGER}");
        }
        
        if (record.getTotal() != null) {
            VALUES("total", "#{total,jdbcType=INTEGER}");
        }
        
        if (record.getExtra() != null) {
            VALUES("extra", "#{extra,jdbcType=VARCHAR}");
        }
        
        if (record.getIndex() != null) {
            VALUES("index", "#{index,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generalcourseinformation
     *
     * @mbggenerated Mon Jun 19 22:16:49 CST 2017
     */
    public String updateByPrimaryKeySelective(GeneralCourse record) {
        BEGIN();
        UPDATE("generalcourseinformation");
        
        if (record.getCode() != null) {
            SET("code = #{code,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getTeacher() != null) {
            SET("teacher = #{teacher,jdbcType=VARCHAR}");
        }
        
        if (record.getCredit() != null) {
            SET("credit = #{credit,jdbcType=INTEGER}");
        }
        
        if (record.getWeek() != null) {
            SET("week = #{week,jdbcType=VARCHAR}");
        }
        
        if (record.getDay_detail1() != null) {
            SET("day_detail1 = #{day_detail1,jdbcType=VARCHAR}");
        }
        
        if (record.getDay_detail2() != null) {
            SET("day_detail2 = #{day_detail2,jdbcType=VARCHAR}");
        }
        
        if (record.getLocation() != null) {
            SET("location = #{location,jdbcType=VARCHAR}");
        }
        
        if (record.getRemaining() != null) {
            SET("remaining = #{remaining,jdbcType=INTEGER}");
        }
        
        if (record.getTotal() != null) {
            SET("total = #{total,jdbcType=INTEGER}");
        }
        
        if (record.getExtra() != null) {
            SET("extra = #{extra,jdbcType=VARCHAR}");
        }
        
        if (record.getIndex() != null) {
            SET("index = #{index,jdbcType=INTEGER}");
        }
        
        WHERE("courseid = #{courseid,jdbcType=VARCHAR}");
        
        return SQL();
    }
}