package com.seeu.user.dao;

import com.seeu.user.model.User;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinformation
     *
     * @mbggenerated Sun Jun 18 22:18:51 CST 2017
     */
    @Insert({
        "insert into userinformation (index, userid, ",
        "password)",
        "values (#{index,jdbcType=INTEGER}, #{userid,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinformation
     *
     * @mbggenerated Sun Jun 18 22:18:51 CST 2017
     */
    @InsertProvider(type=UserSqlProvider.class, method="insertSelective")
    int insertSelective(User record);
}